-- DataStraw CRM Supabase schema
-- Apply this file in the Supabase SQL Editor when migrating from SQLite.
-- Status values intentionally match the existing API contract.

create sequence if not exists ticket_id_seq;

create table if not exists public.tickets (
    id bigint generated by default as identity primary key,
    ticket_id text unique,
    customer_name text not null,
    customer_email text not null,
    subject text not null,
    description text not null default '',
    status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
    priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

-- Keep generated IDs collision-free when this schema is applied after a data import.
select setval(
    'public.ticket_id_seq',
    greatest(coalesce((select max(id) from public.tickets), 0) + 1, 1),
    false
);

create or replace function public.generate_ticket_id()
returns trigger
language plpgsql
as $$
begin
    if new.ticket_id is null or btrim(new.ticket_id) = '' then
        new.ticket_id := 'TKT-' || lpad(nextval('public.ticket_id_seq')::text, 3, '0');
    end if;
    return new;
end;
$$;

drop trigger if exists trg_generate_ticket_id on public.tickets;
create trigger trg_generate_ticket_id
before insert on public.tickets
for each row execute function public.generate_ticket_id();

create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references public.tickets(id) on delete cascade,
    note_text text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_tickets_status on public.tickets(status);
create index if not exists idx_tickets_updated_at on public.tickets(updated_at desc);
create index if not exists idx_notes_ticket_created_at on public.notes(ticket_id, created_at desc);

create or replace function public.set_ticket_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_set_ticket_updated_at on public.tickets;
create trigger trg_set_ticket_updated_at
before update on public.tickets
for each row execute function public.set_ticket_updated_at();

create or replace function public.record_ticket_status_change()
returns trigger
language plpgsql
as $$
declare
    changed_at timestamptz := timezone('utc', now());
    old_label text := case old.status
        when 'open' then 'Open'
        when 'in_progress' then 'In progress'
        when 'resolved' then 'Closed'
    end;
    new_label text := case new.status
        when 'open' then 'Open'
        when 'in_progress' then 'In progress'
        when 'resolved' then 'Closed'
    end;
begin
    if old.status is distinct from new.status then
        insert into public.notes (ticket_id, note_text, created_at)
        values (
            new.id,
            '[System] Status changed from ' || old_label || ' to ' || new_label || ' by Agent at ' ||
                to_char(changed_at at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS') || '.',
            changed_at
        );
    end if;
    return new;
end;
$$;

drop trigger if exists trg_record_ticket_status_change on public.tickets;
create trigger trg_record_ticket_status_change
after update of status on public.tickets
for each row execute function public.record_ticket_status_change();

alter table public.tickets enable row level security;
alter table public.notes enable row level security;

-- The current Express API uses a server-side database connection. Add policies
-- only when exposing Supabase directly to a browser or authenticated client.
comment on table public.tickets is 'Support tickets migrated from the SQLite backend.';
comment on table public.notes is 'Internal notes and system audit entries for tickets.';
